### ISSUE TITLE
Fill opacity documentation incorrect / fill opacity bug

### ISSUE THREAD

**Issue by StevenBiroBS** [protectwise/troika#104]
Setting fillOpacity to zero does not only show the outline as described in the docs:

![image](https://user-images.githubusercontent.com/50342079/108232934-47ec8e00-7111-11eb-88ee-f9f8050c20c4.png)
results in:
![image](https://user-images.githubusercontent.com/50342079/108233448-ca754d80-7111-11eb-8f59-453f948a5fff.png)
and 

![image](https://user-images.githubusercontent.com/50342079/108233092-6e122e00-7111-11eb-8f97-60fe7908dbc3.png)
 results in:
 
![image](https://user-images.githubusercontent.com/50342079/108233528-deb94a80-7111-11eb-8bfb-1680fe3d339c.png)

The outline material blends with the fill when the opacity is set to a value between0 and 1 as well

**Comment by lojjic** [comment]
Ah, yes, I see the confusion. The docs are _technically_ correct -- the solid black you're seeing there _is_ the outline. But it's maybe not clear that the "outline" as currently rendered has a solid interior, it's really more of an expanded text-shadow than just an outline. (I'd considered calling it "shadow' rather than "outline" but I thought that would be too easily confused with Three.js shadows)

What you're going for may be better served by "stroke" rather than "outline", does that work for you?

**Comment by StevenBiroBS** [comment]
> Ah, yes, I see the confusion. The docs are _technically_ correct -- the solid black you're seeing there _is_ the outline. But it's maybe not clear that the "outline" as currently rendered has a solid interior, it's really more of an expanded text-shadow than just an outline. (I'd considered calling it "shadow' rather than "outline" but I thought that would be too easily confused with Three.js shadows)
> 
> What you're going for may be better served by "stroke" rather than "outline", does that work for you?

Thank you so much, that does exactly what I wanted.

I do think that the documentation is a bit confusing around that and could be improved, though since this issue was just in my understanding, I'll close it and open another one about clarifying the outline documentation.
