### ISSUE TITLE
troika-three-text: Performance issue when rendering many Text instances

### ISSUE THREAD

**Issue by daweifeng** [protectwise/troika#117]
Thank you for developing this amazing package! 

I am running into an issue when I try to render 500+ `Text` instances in a scene, the FPS drops a lot. Normally, I would try to use `BufferGeometryUtils.mergeBufferGeometries` to combine all the buffer geometries, but after trying it with the geometries from the `Text` instances, all the texts are not rendered properly. I am not sure if using `BufferGeometryUtils.mergeBufferGeometries` is the right way to optimize the performance for `troika-three-text`. Or, in this case, is there another way to optimize the performance?

Any helps would be appreciated!

**Comment by lojjic** [comment]
Yes, that many instances is going to give poor frame rates due to the number of draw calls.

The problem with combining geometries is that each Text's geometry is itself an instanced geometry, which I don't think `BufferGeometryUtils.mergeBufferGeometries` can handle. So you'd have to not only combine the geometries' vertices but also all their instanced attributes, somehow preserving the world matrix of each instance. And on top of that, every instance is asynchronously processed so you'd have to await them all before merging.

I had started a "MultiText" implementation that did some of this, but didn't finish. That was limited to text within the same plane, however. See here: https://codesandbox.io/s/troika-multitext-wip-jzb1i?file=/src/MultiText.js

Sorry I don't have a better solution for you. 500+ instances rendered in the frustum at once seems like they'd be unreadable anyway, but I don't know your app. Is there opportunity to hide certain texts when there are that many visible?

**Comment by daweifeng** [comment]
Thanks for the suggestions! Yes, I decided to hide some of the texts. Looking forward to your `MultiText` project 👍

**Comment by SrinivasPrabhu794** [comment]
Hi @lojjic,

Is there any chance that the MultiText  feature could be implemented ?
