### ISSUE TITLE
[troika-three-text] Failure loading font

### ISSUE THREAD

**Issue by jashson** [protectwise/troika#120]
Hey there,

when compiling via `gatsby develop` a custom font is getting loaded without any error. But when compiling via `gatsby build` i getting following error during runtime:

```
Failure loading font [customfont.ttf]; trying fallback ReferenceError: i is not defined
...
Failure loading font https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxM.woff TypeError: Cannot read property 'forEach' of undefined
...
```
The font(s) itself gets loaded (network > xhr), but when `troika-three-text` starting to parse a font this error appears.

Do you have any idea, to solve that problem? Maybe `gatsby build` in combination with `gatsby serve` has some problems with service workers, which `troika-three-text` makes use of?

Best regards

Matthias

**Comment by lojjic** [comment]
Hmm, that's concerning. My hunch would be that `gatsby build` is transpiling the JS in a way that makes the font parsing module reference something outside its function, which would break its ability to be shipped to the worker (not a service worker fyi, just a plain old dedicated worker.) This has happened in the past but I've been careful since to avoid anything that would obviously produce that kind of transpilation.

I guess to dig into this further I'll need a way to reproduce it. Would you happen to be able to provide a test I can access, or instructions for making one? Also which version are you using, and if it's the latest 0.41.x then does switching to an older version change things?

**Comment by jashson** [comment]
Thanks for your quick reply. First i would try with an older version. Do you have a tip which version(s) I should test with?

**Comment by lojjic** [comment]
There were quite a few changes to the font parsing code in 0.41 (for bidi/Arabic support), so I'd try 0.40 first. If that doesn't help, maybe try 0.38.1 since r3f/drei was locked on that one for a while and I know a lot of people used it.

[Changelog here](https://github.com/protectwise/troika/blob/master/packages/troika-three-text/CHANGELOG.md) so you can see what changed in each release.

**Comment by lojjic** [comment]
Any updates on the results of downgrading? If this issue was introduced in 0.41 (or regardless, really) I'd like to get to the bottom of it. Thanks.

**Comment by sublambda** [comment]
> Any updates on the results of downgrading? If this issue was introduced in 0.41 (or regardless, really) I'd like to get to the bottom of it. Thanks.

i had a similar issue and downgrading to 0.40 was a sufficient workaround.

the problem in 0.41 is apparently in the bidi parsing code:

Failure loading font ; trying fallback ReferenceError: $jscomp is not defined
    at 3cb4a044-d4d4-45c8-982a-7f55d43e6850:6
    at Array.forEach (<anonymous>)
    at parseData (3cb4a044-d4d4-45c8-982a-7f55d43e6850:6)
    at getBidiCharType (3cb4a044-d4d4-45c8-982a-7f55d43e6850:8)
    at Object.exports.getEmbeddingLevels (3cb4a044-d4d4-45c8-982a-7f55d43e6850:24)
    at 2706a134-a2d6-42a8-b52c-c1d3327f3da3:17
    at 2706a134-a2d6-42a8-b52c-c1d3327f3da3:7
    at 2706a134-a2d6-42a8-b52c-c1d3327f3da3:6
    at Array.forEach (<anonymous>)
    at 2706a134-a2d6-42a8-b52c-c1d3327f3da3:6

**Comment by lojjic** [comment]
@sublambda Thanks! That's very helpful. So this does look like a transpilation issue, there must be something that it's trying to polyfill with an external helper. I just don't know what that would be, but this gives me a starting point to figure it out.

**Comment by lojjic** [comment]
The `$jscomp` in that stacktrace led me to Closure Compiler, so I tried running that locally on bidi-js and I can see the polyfills it's inserting. It looks like they're mostly around array destructuring. I can easily avoid using that, but I think I should have the bidi-js build script perform transpilation down to ES5 anyway so I'm not leaving it up to the quirks of downstream build tools.

**Comment by jashson** [comment]
Sorry for my late reply. I tried with v0.40.0 and as @sublambda already wrote, I have no problems anymore to build and run with Gatsby.

**Comment by lojjic** [comment]
@jashson Thank you for the confirmation. I _think_ I've [fixed the issue in bidi-js](https://github.com/lojjic/bidi-js/commit/ab8d94249fb981f46e961465b0c5905bcc0d32c6), and have published v1.0.2 of that, but still need to update the dependency in troika-three-text. You might be able to try it yourself prior to that if you can force using bidi-js 1.0.2.

**Comment by lojjic** [comment]
Finally got a release out; I'd appreciate verification that troika-three-text v 0.41.2 fixes this issue. Thanks!

**Comment by sublambda** [comment]
ack, 0.41.2 works for me...thanks

**Comment by jashson** [comment]
@lojjic v0.41.2 runs without any issues. Thank you for help and all the work you put into this great peace of software.
