### ISSUE TITLE
[troika-three-text] Glyphs following a curve?

### ISSUE THREAD

**Issue by canadaduane** [protectwise/troika#151]
I'm wondering if it's possible to make a sentence (for example, "Hello kind people of Troika!") that follows a bezier curve. Currently, it seems that a straight line is built in--but there is at least a 'position' instanced attribute that I might be able to tweak on a per-glyph basis, if not a 'rotation'

I've been trying to make my way through the code enough to answer this myself, but I'm having a hard time seeing how each instanced glyph gets assigned a specific position. The `aTroikaGlyphBounds` attribute of GlyphsGeometry seems like the end result of combining a per-glyph position to its bounds. And yet, when I look at the `position` attribute, there are only 4 position coordinates (even for a large sentence). So there's something I'm not connecting. (Perhaps an optimization?)

Anyway... a few questions might help me on my way, in either developing a solution or thinking about it in the "right" way:

1. Would it be possible to generalize curveRadius to a bezier curve? Currently curveRadius seems to assume a specific cylindrical curve type, with the "curve" bending into our out of the Z axis. But it seems at least theoretically possible that a more general curve could apply, with 3 degrees of freedom?

2. If no. 1 is possible, could two bezier curves be used, one for the "top" of the glyphs, and one for the "bottom"? The kind of effect I'm looking for is something like ![this](https://i.ytimg.com/vi/huKLD3lxxe0/maxresdefault.jpg)

3. Am I thinking about this in the wrong way? For example, is there a way to take the "flat geometry" already produced by `troika-three-text` and somehow apply it as a material on a separate geometry, one that I have more control over (e.g. wrapping or "warping" it as needed?

Thanks!

Updated to add: Here is a [three-bmfont-text example](https://tympanus.net/codrops/2019/10/10/create-text-in-three-js-with-three-bmfont-text/) of the kind of versatility or effect I have in mind. The "Ocean" animation is ideal.

**Comment by lojjic** [comment]
Thanks for the questions/suggestions. This sort of thing is almost certainly possible, but I think it would be difficult to design a generic one-size-fits-all solution since there are so many possible ways one might want to apply a curve.

If I were to approach this, I'd probably go for a custom vertex shader, much like your tympanus.net example. Applying custom shaders to troika's `Text` is pretty easy and I've done quite a lot of it -- in fact the current `curveRadius` implementation started out as a custom vertex shader itself which I absorbed into the main API since it was so useful.

Here's an [example using a custom vertex shader to wrap text along a circular path](https://codesandbox.io/s/troika-three-text-custom-circular-shader-5250h?file=/src/App.js). I added some commented out code there for the Ocean effect too.

Applying a bezier curve would be a bit more involved but I think the same approach is sound. The main thing to know is that the `position` attribute in your vertex shader holds the transformed vertex positions. (There's magic behind the scenes which I know makes inspecting the geometry's `position` attribute in JS a bit confusing - by the time that gets to your shader code it's been transformed appropriately.)

If you didn't want to do a custom vertex shader, you could probably also transform the `aTroikaGlyphBounds` array in JS. That becomes the input for transforming the shader's `position` attribute.

There may be corrolary issues like needing to update the geometry's `boundingSphere/boundingBox` to match the transformed bounds for frustum culling.

Ok that's a big brain dump, sorry. Lemme hit your individual questions too:

1. Some genericizing may be possible but I think there's so much variability in use cases that may be hard to design.
2. For sure, you could warp it however you want, as long as you can write the code for it.
3. You're thinking about it in the right way, it's not something that can be applied as a material easily. You *can* do it of course by rendering into a texture, but you wouldn't get the screen-space antialiasing and would be better off just using a 2D canvas texture.

Hope that helps!

**Comment by canadaduane** [comment]
Yes, this is very helpful! Thanks, I will look into these suggestions and see what works for our use case. If anything strikes me as worthy of generalization, I'll come back with something more concrete.
