### ISSUE TITLE
[troika-three-text] suppress warnings

### ISSUE THREAD

**Issue by peterqliu** [protectwise/troika#156]
Great module here. Is it possible to suppress [WorkerModule warnings](https://github.com/protectwise/troika/blob/480ee97426c219195d80733b04092018f9bbca86/packages/troika-worker-utils/src/WorkerModules.js#L150), or better yet, have some control over worker calls so users could spread them out a bit?

**Comment by lojjic** [comment]
Probably yes on both accounts...

I originally thought there was value in trying to detect stuck requests and proactively warn the developer about it, to help guide them toward a hard-to-find issue, but I've become less convinced of that over time. It's probably fine to remove it, especially if it's mostly warning when it shouldn't. I'd accept a PR for removing it.

In terms of "spread them out", I'm interpreting that as allowing a pool of workers that can take requests in parallel...? I've experimented a bit with that and I think it's a good option to have available.

**Comment by lojjic** [comment]
> create lots of Text()s

OK, it helps to know that's what is triggering this for you. (I'd try to reduce that number if you can, but that's another topic...)

The intent of the warning is to catch coding errors where some worker code does not properly return results back to the main thread, or gets in an infinite loop tying up the worker thread, or something like that. The "1000 open requests" is just a proxy for detecting that scenario, and it's obviously not an accurate one. Hence the non-deterministic language -- it's _guessing_ that a large number of open requests is because something is stuck and not emptying the queue, but it could also be because there were just a huge number of requests opened all at once and they haven't had a chance to complete yet (as is your case, it sounds like.)

Yes, this _could_ be worked around by introducing another holding queue prior to submitting to the worker, but I think that would really just be adding complexity. The true fault here is in the warning logic; submitting a lot of requests to the worker should be allowed.

So yeah, I think this has convinced me -- either we need to (a) fix the logic to truly detect "stuck" requests and not large numbers of legitimate requests, or (b) quiet the message. I'm totally fine with (b).

**Comment by peterqliu** [comment]
currently getting a `403` when trying to push a new branch, but I'll take another look later
