### ISSUE TITLE
[troika-three-text] trimming the whitespaces at the end of the text

### ISSUE THREAD

**Issue by eipporko** [protectwise/troika#157]
I'm developing a textfield component and using troika to render the text. 

I found that, if you try to render a text with whitespaces, the size of the bounding box doesn't update until it appears some kind of character at the end.
 
For example if you write one or more whitespaces at the end of the text ("      "), the x size of the bounding box is equal to 0 or doesn't  update, but when you add something at the end ("      .") the size seems to be the correct, taking into account the number of whitespaces at the beginning of the string.

Is it possible that it exists some kind of trim at the end of the text to render? Could this behaviour be disabled in any way?

Video related: [https://youtu.be/A8ti9uRWZFo](https://youtu.be/A8ti9uRWZFo)

**Comment by lojjic** [comment]
Thanks for the video, that's very helpful.

Assuming you're talking about the `geometry.boundingBox`, it's by design that it only encompasses the visually rendered parts of the text.

It looks like you're trying to use those bounds to place a caret for text input? If so, you probably want to use the supplied caret positioning data, since that's more robust (handles multiple lines, RTL, etc.) There are a couple [utility methods](https://protectwise.github.io/troika/troika-three-text/#carets-and-selection-ranges) for getting caret positions and selection range bounds. There's also [`textmesh.textRenderInfo.caretPositions`](https://github.com/protectwise/troika/blob/1b20e34e13fd6de7aa8257b8e50f0db671e4c964/packages/troika-three-text/src/TextBuilder.js#L78) which you can access directly.

**Comment by eipporko** [comment]
Thanks, 

Yes I was trying to use the bounding box to place some kind of cursor/caret, I will take a look into caretPositions property.

My doubt with the bounding box was that the whitespaces at the beginning of the string were encompassed inside it, but not the whitespaces at the end.

**Comment by eipporko** [comment]
Hello and sorry for the delay in the response.

I couldn't try the caretPositions property until today, but now works as expected =). 

For my side I consider the issue closed :-)

Video related: https://youtu.be/G8PDsRvpIHk](https://youtu.be/G8PDsRvpIHk)
