### ISSUE TITLE
Does Troika make sense for 2D WebGL projects?

### ISSUE THREAD

**Issue by viztastic** [protectwise/troika#166]
Hi, i'm looking to build a collaborative flow charting app and wondering if Troika is the right tool to be using.

Is there an inherent performance overhead because Troika is 3D focused or not really?

Sorry I am quite new to WebGL so it might be a dumb question to begin with

Thanks in advance!

**Comment by lojjic** [comment]
Hi, thanks for asking. I think the answer depends on your needs. WebGL can definitely be a great tool for 2D not just 3D, it's really all the same just with a different type of camera. I've done a lot of work using troika-3d to create 2D visualizations with a fallback to 2D canvas using the troika-2d package. So it's definitely possible.

If you're looking to go down the WebGL route, I'd suggest getting familiar with Three.js first, try building a few things with it on its own and then look into adding a framework on top later. If you're using React then I'd highly suggest [react-three-fiber](https://docs.pmnd.rs/react-three-fiber/) since there's a large community around it. While Troika is very capable and better optimized in some specific ways, there's almost no community to speak of and I won't be able to provide support.

**Comment by viztastic** [comment]
Thanks so much for the kind and super helpful response. 

I'm looking to build a flow-charting app of sorts. I expect there to be hundreds of nodes hence why I'm considering WebGL as opposed to straight-up canvas.

I'm very much scouting for technologies at this stage, if I get financial backing for the project I'd be happy to consider becoming a sponsor to help build up the support base.
