### ISSUE TITLE
[troika-three-text] sometimes the text is incomplete

### ISSUE THREAD

**Issue by Bowen7** [protectwise/troika#188]
When I use troika-three-text with three.js `0.136.0`, sometimes the text is incomplete.
But `0.135.0` is fine.
https://codesandbox.io/s/upbeat-brook-h5dlp2?file=/src/App.js

**Comment by lojjic** [comment]
Thanks for the report. This appears to be fixed in v 0.46 which I just released - here's an [updated sandbox](https://codesandbox.io/s/festive-bhaskara-8zhcd6?file=/src/App.js) using it.

---

For posterity: Three.js r136 [changed how they initialize/upload DataTextures](https://github.com/mrdoob/three.js/pull/22947) in WebGL2. The new method using `texStorage2D` is presumably more efficient, but makes the texture's dimensions immutable whereas the old method allowed resizing. Since we need to resize the SDF texture when the number of glyphs exceeds its initial size, this started failing.

In troika-three-text v 0.46 this is no longer a problem because the SDF generation was rewritten to utilize the GPU and no longer uses a DataTexture.

**Comment by lojjic** [comment]
Turned out this issue was still present in 0.46, the `texStorage2D` change affects all textures not just data textures. I've published 0.46.2 with a fix that disposes the texture when resizing it, so that it gets reallocated on the GPU at the new size.

**Comment by lojjic** [comment]
Also in case you can't update to 0.46, or encounter issues with the rewritten SDF generator, I've also published patch release 0.45.1 which contains the same fix.

**Comment by Bowen7** [comment]
Thanks a lot!
