### ISSUE TITLE
Text based on viewport width

### ISSUE THREAD

**Issue by souporserious** [protectwise/troika#194]
Hello again, curious if there is a simple way to base the font size on the viewport width? I noticed in the docs it says it uses the local world units, am I correct that it's based on the viewport height world unit? I'm trying to align the text to a baseline, and not sure if this is configurable in ThreeJS somehow or in this library (I'm still relatively new to everything 😇). I'm able to [achieve this in R3F](https://codesandbox.io/s/drei-text-viewport-width-u0l4vg?file=/src/App.tsx) right now, but it's pretty jumpy when resizing the height since I believe they are competing with each other:

```tsx
function Scene() {
  const { viewport } = useThree();
  const fontSize = viewport.width / 10;
  return (
    <Text fontSize={fontSize} color="black">
      Hello World
    </Text>
  );
}
```

**Comment by lojjic** [comment]
> I noticed in the docs it says it uses the local world units, am I correct that it's based on the viewport height world unit?

It's the 3D coordinate system's units, same as if you were setting a sphere's radius or a box's width. It has no concept of a "viewport", that's something that only your application knows about.

I'm not sure what the jumpiness is about, maybe it's lag because you're changing the fontSize on each resize and it has to recalculate the text asynchronously so you see it briefly at the old size? Consider giving it a constant fontSize and changing its scale instead, that should perform better. Like [here](https://codesandbox.io/s/drei-text-viewport-width-forked-84vebv?file=/src/App.tsx)

**Comment by souporserious** [comment]
Ah this makes so much sense, still getting used to these relative units coming from web 2D! Thank you for taking a look, much appreciated! 🙏
