### ISSUE TITLE
block and visible bounds not accounting scale or position

### ISSUE THREAD

**Issue by souporserious** [protectwise/troika#195]
Apologies if this is an R3F specific issue, but it seems `scale` and `position` are not taken into account when returning the bounds in `onSync`. I noticed this first in a larger project I'm working on when I set a `group` position higher in the tree which threw off the bounds. I can account for this myself if needed, but wasn't sure if it's a bug or not. Please see [this Codesandbox](https://codesandbox.io/s/drei-text-bounding-box-position-2lifsh?file=/src/App.tsx) that shows the issue.

**Comment by lojjic** [comment]
Hi! You're right, the bounds are static and are local to the text object's coordinate system. This is intentional, it's just like the boundingSphere or boundingBox of a Three.js geometry. If you want to get bounds in world space then you'll have to apply the object's world matrix to it. Hope that helps.

**Comment by souporserious** [comment]
Ah ok, good to know! I'll do more research on how to apply the world matrix, thank you!
