### ISSUE TITLE
Support curveRadius around y-axis (in addition to current z-axis curve)

### ISSUE THREAD

**Issue by sdl60660** [protectwise/troika#200]
I'm working on a project right now where I have troika text labeling somthing on the surface of the earth, and wish I was able to curve the text around the surface. I know I can curve it "vertically", but would like it be able to do the equivalent of wrapping it around a cylinder or sphere. I can set it in a particular position so that it appears to lay flat on the surface of the sphere, but if the camera moves much, it's clear that that's not the case.

Not a huge deal, but thought I'd suggest it since it would be helpful.

**Comment by lojjic** [comment]
Thanks for the suggestion. I've included the horizontal curvature as a core feature because it's a very common need, but I'm not sure the same applies for vertical/spherical curvature, though I'm open to being convinced. I'd rather not introduce more complexity in the core if it's not very common.

Luckily you can apply any custom shader material yourself, including vertex transforms. For custom surface shapes that's how I'd recommend you do it, I've seen people doing that for text along paths, on wavy clothlike surfaces, etc. Here's a quick-and-dirty spherical curve example using `createDerivedMaterial`: https://codesandbox.io/s/troika-three-text-spherical-curvature-tv31bn?file=/src/App.js - feel free to use that as a starting point.

I'm going to close this for now as wontfix, but I'm open to further discussion on it.

**Comment by sdl60660** [comment]
Ah yeah, that example totally did the trick. Easy for me to say it, but feels like it doesn't add much complexity/cognitive "weight" as a prop if there's already curviture introduced along another axis, but this is a great/easy example on how to it on my own. Thanks!

**Comment by sdl60660** [comment]
Since I've been using this fix, things work great locally, but the text doesn't seem to render after running through a build step and I get this error related to the shader in my console:

```
react_devtools_backend.js:3973 THREE.WebGLProgram: Shader Error 1282 - VALIDATE_STATUS false

Program Info Log: Vertex shader is not compiled.

VERTEX

ERROR: 0:63: 'troika_position_1' : redefinition
ERROR: 0:64: 'troika_normal_1' : redefinition
ERROR: 0:65: 'troika_uv_1' : redefinition
ERROR: 0:423: 'troikaVertexTransform1' : function already has a body
ERROR: 0:469: 'troikaOrigMain1' : function already has a body
```

Is that something people have encountered before with an easy fix? Or is that out of scope for this libarary and related to the implementation from that codesandbox example that I ripped?

**Comment by lojjic** [comment]
Hmm, that looks like it's trying to double-derive the text shader material. I can't think why that would happen, especially if it only happens with a build step in place. 🤔

**Comment by sdl60660** [comment]
Ah, I think you nailed it. From the package-lock:
![Screen Shot 2022-03-29 at 1 45 17 PM](https://user-images.githubusercontent.com/12772904/160673198-04c291f2-b443-4768-acd4-5d299e45a846.png)

I installed `troika-three-utils` for the `createDerivedMaterial` method. Could this be imported direclty from `troika-three-text` or from `drei`?

**Comment by sdl60660** [comment]
Ah nevermind, I'll just pin the version on the install I guess
