### ISSUE TITLE
MSDF support?

### ISSUE THREAD

**Issue by Emnolope** [protectwise/troika#254]
Will troika ever have msdf support? How would I start to implement it myself? three-bmfont-test has msdf support and the texture is in the file msdf.js, but it's also ancient.

**Comment by lojjic** [comment]
What sort of improvement are you looking for from MSDF?

I'm definitely not against it, if it can be generated client side with similar performance (i.e. using the GPU).

My previous attempts have resulted in slower performance due to extra JS processing required, visual artifacts (likely me not getting the algorithm quite right), and haven't shown a significant improvement over just increasing the single-channel SDF dimensions.

If you wanted to take a shot at it, [webgl-sdf-generator](https://github.com/lojjic/webgl-sdf-generator/) would be the place to do it. :)

**Comment by crystalthoughts** [comment]
The artifacts are likely due to overlaps in the font file. The shapes need to be properly booleaned (apart from the holes in O for example). msdfgen could potentially be ported to wasm if it isn't already. Maybe blend2d would work for processing the fonts (skia also has a module for this but skia's massive).

I think this would be a great improvement for things like very large text and sharp corners, which is what msdf looks to fix!
Happy to help with it at some point.

**Comment by lojjic** [comment]
Great, I'm definitely open to evaluating a submitted implementation. My criteria for accepting it would be that it brings better quality than just upping the sdfGlyphSize (image below with sdfGlyphSize=256, for example, giving much sharper corners) without much worse performance (e.g. 82 glyphs of Roboto at sdfGlyphSize=256 takes 22 milliseconds).

![image](https://user-images.githubusercontent.com/138124/234657129-6387eca0-47f9-4792-9b36-68001f4d492b.png)
