### ISSUE TITLE
Setting customDepthMaterial on InstancedUniformsMesh

### ISSUE THREAD

**Issue by mileshiroo** [protectwise/troika#260]
Hi, 

My instanced uniforms mesh has a vertex shader animation applied to it. I'd like the shadows to be able to match the mesh as it animates.

I get an error when I try to set customDepthMaterial on the InstancedUniformsMesh, and I can see in [the code](https://github.com/protectwise/troika/blob/55538664c9f25c5afea5fac53e4df2517d1f20bc/packages/three-instanced-uniforms-mesh/src/InstancedUniformsMesh.js#L67) that there is only a getter for customDepthMaterial and no way to set it.

Is there any way to set a customDepthMaterial?

Thanks!

**Comment by mileshiroo** [comment]
It's not, no. The shadow shows the original geometry prior to vertex transformation. FWIW I'm using [this](https://github.com/FarazzShaikh/THREE-CustomShaderMaterial) for my custom materials, maybe that has something to do with it?

**Comment by mileshiroo** [comment]
I just switched one of the animated materials to a THREE.ShaderMaterial instead of a CustomShaderMaterial and the same issue with the shadows is present.

**Comment by lojjic** [comment]
Ah, ok, I see ...

The auto-depthmaterial creation is handled in [Troika's DerivedMaterial](https://github.com/protectwise/troika/blob/main/packages/troika-three-utils/src/DerivedMaterial.js#L224), and it will properly chain them if it's DerivedMaterials all the way down, but not with CSM or THREE.ShaderMaterial since they don't provide auto depth materials.

I think if you added a `getDepthMaterial()` method to your material instance, it would pick that up and work properly...?

I also think your initial request is correct, too -- that InstanceUniformsMesh should allow setting customDepthMaterial, since the auto-depthmaterial behavior might not always be desired.

**Comment by mileshiroo** [comment]
Got it, I switched my material over to a DerivedMaterial—used the customRewriter function to rewrite the entire thing—and the shadows now work as intended. Thanks for the help!
