### ISSUE TITLE
troika-three-text: Kerning is off

### ISSUE THREAD

**Issue by michaelthatsit** [protectwise/troika#289]
We're working on a webcomponents library that pretty heavily incorporates troika-three-text. I only recently noticed that the kerning is ever so slightly off. Here I have troika-three-text overlayed ontop of the same text in pure HTML, same font, weight, and size.

![Screenshot 2023-12-05 at 4 30 30 PM](https://github.com/protectwise/troika/assets/19628643/594fce35-f7ac-4552-b3f7-fc14e10d1013)

The font size is correct as the line up perfectly in terms of height. is there anyway to directly tune the kerning?

**Comment by lojjic** [comment]
It shouldn't differ. Can you provide that testcase?

**Comment by michaelthatsit** [comment]
It might take me a bit. I could also share a link to the branch of the project itself?

here's the repo: https://github.com/Volumetrics-io/mrjs/tree/160-layout-bugs

Here's where we're applying the style: https://github.com/Volumetrics-io/mrjs/blob/3cf762848dcd9f5d7a7409bb5e625e801cdc0913/src/component-systems/TextSystem.js#L83

**Comment by michaelthatsit** [comment]
If you pull the repo and run `npm install && npm run server` you'll see the content rendered on top of the same DOM content.

**Comment by michaelthatsit** [comment]
fixed a minor bug on my end that appears to make it slightly better but it still seems off.

**Comment by michaelthatsit** [comment]
CLosing this, very certain at this point its my own conversion that's wrong.

**Comment by lojjic** [comment]
The bulk of the issue seems to be that they're actually not the same font -- if I set it to the Roboto-Regular.ttf in your repo the character spacing looks correct, though there's a difference in vertical line spacing but that can be adjusted.

<img width="795" alt="image" src="https://github.com/protectwise/troika/assets/138124/0cba4b09-bf96-492f-918b-10b46f301a9e">

It does seem like the recent change from Roboto to Noto Sans as the default font hasn't been properly documented, so it's understandable why you'd think it was Roboto.

**Comment by michaelthatsit** [comment]
Oh so troika is using Noto Sans?

**Comment by lojjic** [comment]
Yeah, it uses Noto fonts as the default so it can get full(ish) Unicode support with a single font family. This was a recent change, which I failed to document properly, apologies!

Also, it looks like vertical spacing does match after all, it was just wrapping differently because t-t-t honors newlines. If I remove all the newlines it matches up other than a 1px-ish difference in the vertical starting point.

<img width="783" alt="image" src="https://github.com/protectwise/troika/assets/138124/22de5232-8d48-48b6-b026-dc0c5d4d3ea4">
