### ISSUE TITLE
Glitches when used with Montserrat

### ISSUE THREAD

**Issue by AyymericArn** [protectwise/troika#310]
Hello, when using Montserrat (with any type of font-weight), I face those artifacts :
![image](https://github.com/protectwise/troika/assets/32864333/8f7dd1ca-2f8b-46e5-8e1d-987cde321d66)
(weird triangles on the Z, the R, the A and the G)

I tried using both .woff and .ttf.

This effect seem not to be visible on other fonts (I tried with Noto Sans).

I am not using any special property apart from `font` and `color`. My Three scene does not have any particular. Also tried on a minimal scene.

Link to the font : https://fonts.gstatic.com/s/montserrat/v26/JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCvC70w9.woff

**Comment by AyymericArn** [comment]
Actually seems to be provoked by the font-file itself. The glitch disappears when switching to another version of the Montserrat font file grabbed from https://font.download/. Closing as the glitch does not seem to be related to the library

**Comment by lojjic** [comment]
I'm glad you found an alternate version of the font that works. Those artifacts are due to the font containing overlapping paths, which are supposed to be removed by the font author but they sometimes remain. There's some prior discussion on this in [#57](https://github.com/protectwise/troika/issues/57#issuecomment-640703080).
