### ISSUE TITLE
Build error in FontProcessor

### ISSUE THREAD

**Issue by ryanking1809** [protectwise/troika#51]
When I `build` with `create-react-app` I get the error `ReferenceError: s is not defined` with the `FontProcessor` file. I suspect something is breaking during minification?

---

EDIT:  Looks like `textmesh-standalone.esm.js` gets this error, however, `textmesh-standalone.umd.js` works fine. Quite possibly the same issue with codesandbox?

**Comment by lojjic** [comment]
I'll gladly take a look at this. Can you provide a bit more detail about your `create-react-app` setup, or point me to a repo or zip that demonstrates it?

**Comment by ryanking1809** [comment]
Thanks Jason, will through together something simple for you to look at tomorrow.

**Comment by ryanking1809** [comment]
Ok, this should do it. I've just created a TextMesh element in the app.js file. 
Just run:

```
yarn build
serve -s build
```

[textmesh-build.zip](https://github.com/protectwise/troika/files/4711900/textmesh-build.zip)

**Comment by lojjic** [comment]
That's perfect, thanks! I see what's going on, there's some code that runs in the web worker that is getting polyfilled (array destructuring in this case) in a way that uses a global function. The technique I use for running code in the worker isn't resilient to that sort of thing.

This should be a simple fix - I can just change that code to avoid the destructuring. But I also need to find a way to avoid running into this again in the future, since it's not the first time it's bitten me. :/

**Comment by ryanking1809** [comment]
Oh right, I'm not sure about how to avoid that one. Regardless, using the umd.js file isn't big deal so feel free to take your time. Thanks for your help!
