### ISSUE TITLE
troika-three-text 0.33.1: Reference error in troika-worker-utils.esm.js

### ISSUE THREAD

**Issue by n1ru4l** [protectwise/troika#84]
The error started showing up, after upgrading to the latest version `0.33.1`. The issue is resolved after downgrading to `0.32.0`.

It seems like a dependency might be missing, `troika-worker-utils` seems to have no dependencies listed.

```
troika-worker-utils.esm.js:564 Uncaught (in promise) Error: Error in worker registerModule call: C_Users_lauri_Projects_dungeon_revealer_node_modules_babel_preset_react_app_node_modules_babel_runtime_helpers_esm_toConsumableArray__WEBPACK_IMPORTED_MODULE_0__ is not defined
    at openRequests.<computed> (troika-worker-utils.esm.js:564)
    at Worker.worker.onmessage (troika-worker-utils.esm.js:550)
openRequests.<computed> @ troika-worker-utils.esm.js:564
worker.onmessage @ troika-worker-utils.esm.js:550
Promise.then (async)
getTextRenderInfo @ troika-three-text.esm.js:4438
sync @ troika-three-text.esm.js:5194
(anonymous) @ canvas-text.tsx:94
commitHookEffectListMount @ react-reconciler.development.js:11005
commitLifeCycles @ react-reconciler.development.js:11061
commitLayoutEffects @ react-reconciler.development.js:14216
callCallback @ react-reconciler.development.js:10632
invokeGuardedCallbackDev @ react-reconciler.development.js:10681
invokeGuardedCallback @ react-reconciler.development.js:10733
commitRootImpl @ react-reconciler.development.js:13954
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority @ react-reconciler.development.js:1752
commitRoot @ react-reconciler.development.js:13794
finishSyncRender @ react-reconciler.development.js:13192
performSyncWorkOnRoot @ react-reconciler.development.js:13178
(anonymous) @ react-reconciler.development.js:1802
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority @ react-reconciler.development.js:1752
flushSyncCallbackQueueImpl @ react-reconciler.development.js:1797
flushSyncCallbackQueue @ react-reconciler.development.js:1785
flushPassiveEffectsImpl @ react-reconciler.development.js:14296
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority @ react-reconciler.development.js:1752
flushPassiveEffects @ react-reconciler.development.js:14233
(anonymous) @ react-reconciler.development.js:14112
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
````

**Comment by lojjic** [comment]
Thanks for the report. Based on the stack trace, what I think is happening is that your Webpack module loader is now resolving to the .esm.js file rather than the .umd.js file (this was an intentional change in 0.33). That esm file is not pre-transpiled, so something in there is now getting transpiled by your Babel step in a way that uses external helper functions, which fails with the way troika-three-text shuts work off to a web worker thread.

I think the fix here is that I need to find the piece(s) of worker code that's requiring transpilation, and downgrade it to ES5 in the source. I'll also look into some sort of CI tool that can detect future cases like this prior to publication.

In the meantime, you may be able to work around it by forcing Webpack to resolve to the .umd.js file for each of the three troika packages, but I'm guessing staying on 0.32 for now is fine.

**Comment by n1ru4l** [comment]
Hm I am using create-react-app, so this must be fixed here I guess 😓

**Comment by lojjic** [comment]
This error should be gone in 0.34.0, just released. Please reopen if you still see if happening.
