### ISSUE TITLE
sync() callback is before a drawing can actually happen.

### ISSUE THREAD

**Issue by FunMiles** [protectwise/troika#98]
I think this issue is related to some of the comments I've made before when I used this project under react.
The text does not always appear when rendering _on demand_ using `drei`.

I've just started using this project in a `svelte` version of my app (discovered [svelte](https://svelte.dev/tutorial/basics) recently and love its easier reactivity than `react`).
In any case, I use the `Text.sync( callback )` to re-render the frame. However it does not work. The text is not yet ready to render at this point.

Would it be possible to get a callback when a render would actually not be a `no-op` ?

PS: Still loving this package. Thanks again for making it. I am progressing in my svelte experience and will likely make my svelte `Three` work available on github and that will include use of this project for text.

**Comment by lojjic** [comment]
Very cool about Svelte! I'd love to see your integration work, I'm very interested in reactive models like theirs.

As written, a callback passed to `sync` is only be invoked after the processing thread returns new values and the geometry is updated - see [this code](https://github.com/protectwise/troika/blob/2ae29faffcec2302453ce9dabac633ade8181127/packages/troika-three-text/src/Text.js#L340). I can't think of a reason your callback would be called without having updated render info. Can you confirm that's what you're indeed seeing?

There _are_ some scenarios where the callback will _not_ be called -- namely if something else calls sync and receives a response before you call sync. If you're making sure to call sync as soon as you update the text config properties, this situation shouldn't occur. But this didn't sound like what you're observing anyway, right?

Regardless, I'd probably recommend not using a callback on every sync call, and instead adding a single listener for [the `synccomplete` event as described here](https://github.com/protectwise/troika/tree/master/packages/troika-three-text#handling-asynchronous-updates) - that should remove any question of multiple callbacks encountering race conditions.

**Comment by FunMiles** [comment]
I am pretty sure this is what I am seeing. i.e. The callback is called, my callback routine does a render and the text is not rendered. A render later, the text appears.

When I have more time. I will create a tiny svelte/three example with the way I've implemented the text.
Hopefully it will exhibit the same phenomenon and you can see it yourself. Or I find that I have a bug 😛

**Comment by FunMiles** [comment]
Have a look at this. It is a very quick setup but you should see just a black screen. To see what's in it, just click in the window and move around (it spins).
Every time you click the button, it adds a text at a random location on a sphere. Notice that the latest text does not appear, but the one before that does. Again, to make the latest one appear, move the mouse in the drawing while clicking.

https://github.com/FunMiles/SvelteThreeText

**Comment by lojjic** [comment]
Thanks for the example. I think there's some quirk about Svelte's reactivity that's causing your issue. Here's what I see:

At the time you call `sync(yourcallback)`, the Text instance doesn't appear to have any of its properties set: `.text` is empty, `font` is null, etc... So your callback is invoked with the results of processing empty text. The Text mesh is in the scene but all its geometry arrays are empty.

Then you call your followup render, which triggers Text's onBeforeRender handler, which itself issues a `sync()` call (without any callback) as a backup in case the author forgot to call it. At that point the Text has all its properties properly configured, so its result is no longer empty. But since that sync call didn't have a callback, it doesn't schedule a re-render. As soon as another render occurs (e.g. via drag), it becomes visible.

Does that make sense? Not being too familiar with svelte's reactivity model, I'm assuming all those reactive props are async or something.

I do think if you use the `synccomplete` event instead of relying on the callback you'll catch all updates regardless of who issued the sync.

**Comment by FunMiles** [comment]
@lojjic You are actually correct. It seems that the reactive statement with `$:` do not get called until AFTER the set of statements without reactivity have been all done.
I'm also rather fresh with svelte and the order of some of those things has surprised me as well over the weekend.
I found two ways of fixing the issue:

1.  Adding a copy of the reactive statement `$: myText.text = text;` without the `$:`. To be honest, I need to investigate the reactivity of statements that depend on element properties. I put the `$:` to make sure things would be updated.
2. Making the `myText.sync()` become reactive.

I will investigate if the reactivity is necessary or if simply changing the property 'text' will trigger a re-run of the statements that depend on it (my initial understanding is that it probably does not).

Let me ask you one important thing though. You mention (as is said in the docs) that `sync()` is called by the rendering. However it is an async call, so it has no effect for the immediate rendering that called it. Is that right?
I think this might probably be the cause of the same kind of issue I saw under 'drei' ?
In any case, I now have a solution. I will push an updated version this afternoon.

**Comment by lojjic** [comment]
> You mention (as is said in the docs) that sync() is called by the rendering. However it is an async call, so it has no effect for the immediate rendering that called it. Is that right?
I think this might probably be the cause of the same kind of issue I saw under 'drei' ?

Yes, that is correct. That fallback call requires something else to trigger another render, it can't do it itself.

But I don't think that's an issue in drei, because it calls sync in a useLayoutEffect hook which is (IIUC) synchronously called after any change to the props. So the fallback sync should always be a no-op there.

**Comment by FunMiles** [comment]
Does the `addEventListener('synccomplete', () => {...})` require removal when disposed to avoid memory leak?

**Comment by lojjic** [comment]
I don't think so; I believe the reference to the handler is stored on the mesh itself (this is a ThreeJS thing), so as soon as all references to your mesh are removed both it and your handler should be GCable. But explicitly removing it wouldn't hurt I suppose.

**Comment by lojjic** [comment]
Can this issue be closed?

**Comment by FunMiles** [comment]
Yes I'm closing it.
